config/routes.rb
Rails.application.routes.draw do
  root to: 'welcomes#index'

  devise_for :patients
  devise_for :doctors

  resources :slots do
    post :book, on: :member
  end
  resources :appointments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :slot
  belongs_to :patient
  has_one :doctor, through: :slot

  after_commit :book_slot, on: :create
  after_commit :unbooked_slot, on: :destroy

  def book_slot
    slot.update(booked: true)
  end

  def unbooked_slot
    slot.update(booked: false)
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :slots
  has_many :appointments, through: :slots
  has_many :patients, through: :appointments

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :slots
  has_many :doctors, through: :slots

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/slot.rb
class Slot < ApplicationRecord
  has_one :appointment
  belongs_to :doctor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :mobile])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :mobile])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.fetch(:appointment, {})
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy, :book]
  before_action :verify_doctor_authorization!, except: [:index, :book]

  def index
    @slots = if current_doctor.present?
      current_doctor.slots
    elsif current_patient.present?
      Slot.where(booked: false)
    end
  end

  def show
  end

  def new
    @slot = current_doctor.slots.new
  end

  def edit
  end

  def create
    @slot = current_doctor.slots.build(slot_params)
    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book
    @appointment = @slot.build_appointment(patient_id: current_patient.id)
    if @appointment.save
      respond_to do |format|
        format.html { redirect_to @appointment, notice: 'Appointment has been booked successfully.' }
        format.json { render :show, status: :ok, location: @appointment }
      end
    else
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_slot
    @slot = if current_doctor.present?
      current_doctor.slots.find(params[:id])
    else
      Slot.find(params[:id])
    end
  end

  def slot_params
    params.fetch(:slot, {}).permit(:from_time, :to_time, :date)
  end

  def verify_doctor_authorization!
    if current_doctor.blank?
      respond_to do |format|
        format.html { redirect_to roots_url, notice: 'Unathorized Access.' }
        format.json { render json: {message: 'Unathorized Access.'}, status: :unprocessable_entity }
        # format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th> Doctor Name </th>
      <th> From Time </th>
      <th> To Time </th>
      <th> Date </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.slot.doctor.full_name%></td>
        <td><%= appointment.slot.from_time%></td>
        <td><%= appointment.slot.to_time%></td>
        <td><%= appointment.slot.date.to_date%></td>
        <td><%= link_to 'Cancell Appointment', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<h3>Appointment</h3>
<% if current_doctor.present? %>
    <label>Patient Name: </label>
    <%= @appointment.patient.full_name %>
<% elsif current_patient.present? %>
    <label>Doctor Name: </label>
    <%= @appointment.doctor.full_name %>
<% end %>
<br>
<label>From Time: </label>
<%= @appointment.slot.from_time %>
<br>
<label>To Time: </label>
<%= @appointment.slot.to_time %>
<br>
<label>Date: </label>
<%= @appointment.slot.date.to_date %>
<br>
<br>
<!-- <%= link_to 'Edit', edit_appointment_path(@appointment) %> | -->
<%= link_to 'Back', appointments_path %>

app/views/layouts/_doctor_navbar_links.erb
<ul class="nav navbar-nav">
  <% if current_doctor %>
    <li>
      <%= link_to "Check Schedule", slots_path%>
    </li>
  <% end %>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_doctor %>
    <li><%= link_to "Profile", edit_doctor_registration_path %></li>
    <li><%= link_to "Log Out", destroy_doctor_session_path, method: "delete" %></li>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Handy Health", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_patient %>
        <%= render partial: 'layouts/patient_navbar_links' %>
      <% else %>
        <%= render partial: 'layouts/doctor_navbar_links' %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_patient_navbar_links.erb
<ul class="nav navbar-nav">
  <% if current_patient %>
    <li>
      <%= link_to "Available Slots", slots_path%>
    </li>
    <li>
      <%= link_to "Booked Appointments", appointments_path%>
    </li>
  <% end %>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_patient %>
    <li><%= link_to "Profile", edit_patient_registration_path %></li>
    <li><%= link_to "Log Out", destroy_patient_session_path, method: "delete" %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HandyHealth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "welcome", media: "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="container">
      <% if notice %>
        <p class="alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert-alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
        <% slot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :from_time %><br />
    <%= form.text_field :from_time%>
  </div>
  <div class="field">
    <%= form.label :to_time %><br />
    <%= form.text_field :to_time%>
  </div>
  <div class="field">
    <%= form.label :date %><br />
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<h1>Slots</h1>
<% if @slots.present? %>
  <table>
    <thead>
      <tr>
        <th> From Time </th>
        <th> To Time </th>
        <th> Date </th>
        <% if current_doctor.present? %>
          <th>Appointment</th>
          <th colspan="2"></th>
        <% elsif current_patient.present? %>
          <th>Doctor Name</th>
          <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @slots.each do |slot| %>
        <tr>
          <td><%= slot.from_time %></td>
          <td><%= slot.to_time %></td>
          <td><%= slot.date.to_date %></td>
          <% if current_doctor.present? %>
            <% if slot.appointment.present? %>
              <td><%= link_to 'View Appointment', slot.appointment %></td>
            <% else %>
              <td>Not yet booked</td>
            <% end %>
            <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
            <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% elsif current_patient.present? %>
            <td><%= slot.doctor.full_name %></td>
            <td><%= link_to 'Book Appointment', book_slot_path(slot), method: :post %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <% if current_doctor.present? %>
    <h3>Slots are empty, please add some slots.</h3>
  <% elsif current_patient.present? %>
    <h3>Sorry, Currently Doctors are not available</h3>
  <% end %>
<% end %>

<br>
<% if current_doctor.present? %>
  <%= link_to 'New Slot', new_slot_path %>
<% end %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<!-- <%= link_to 'Edit', edit_slot_path(@slot) %> | -->
<%= link_to 'Back', slots_path %>

app/views/welcomes/index.html.erb
<% if current_patient.blank? && current_doctor.blank? %>
  <div class="login_page">
    <div class="homePageButtons">
      <div>
        <a href=<%= new_session_path(:patient)%>>
          <input type="button" name="PATIENT" value="I AM PATIENT" >
        </a>
      </div>
      <div >
        <a href=<%= new_session_path(:doctor)%>>
          <input type="button" name="DOCTOR" value="I AM DOCTOR" >
        </a>
      </div>
    </div>
  </div>
<% end %>